# Azure DevOps pipeline for Azure deployment

variables:
- group: globomantics

trigger:
  branches:
    include:
    - main

stages:
- stage: development
  displayName: development
  jobs:
  - deployment: deploy
    environment: development
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'
      
          # Init
          - task: TerraformTaskV2@2
            displayName: Initialize Terraform
            env:
              ARM_SAS_TOKEN: $(sas_token)
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/networking'
              commandOptions: '-backend-config=storage_account_name=$(storage_account_name) -backend-config=container_name="terraform-state" -backend-config=key="terraform.tfstate"'
              provider: 'azurerm'
      
          # Check for workspace
          - task: Bash@3
            displayName: Check for Workspace
            inputs:
              targetType: 'filePath'
              filePath: '$(System.DefaultWorkingDirectory)/networking/workspacetest.sh'
              arguments: '$(Environment.Name)'
      
          - task: TerraformTaskV2@2
            displayName: Plan Terraform Deployment
            env:
              TF_WORKSPACE: '$(Environment.Name)'
              TF_VAR_sec_client_secret: $(sec_client_secret)
              ARM_SAS_TOKEN: $(sas_token)
              TF_VAR_sec_sub_id: $(sec_sub_id)
              TF_VAR_sec_client_id: $(sec_client_id)
              TF_VAR_sec_tenant_id: $(sec_tenant_id)
              TF_VAR_sec_vnet_name: $(sec_vnet_name)
              TF_VAR_sec_vnet_id: $(sec_vnet_id)
              TF_VAR_sec_resource_group: $(sec_resource_group)
              TF_VAR_sec_principal_id: $(sec_principal_id)
            inputs:
              command: 'plan'
              commandOptions: '-out main.tfplan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/networking'
              environmentServiceName: 'Networking_Sub'
      
          - task: TerraformTaskV2@2
            displayName: Apply Terraform Deployment
            env:
              TF_WORKSPACE: '$(Environment.Name)'
              TF_VAR_sec_client_secret: $(sec_client_secret)
              ARM_SAS_TOKEN: $(sas_token)
              TF_VAR_sec_sub_id: $(sec_sub_id)
              TF_VAR_sec_client_id: $(sec_client_id)
              TF_VAR_sec_tenant_id: $(sec_tenant_id)
              TF_VAR_sec_vnet_name: $(sec_vnet_name)
              TF_VAR_sec_vnet_id: $(sec_vnet_id)
              TF_VAR_sec_resource_group: $(sec_resource_group)
              TF_VAR_sec_principal_id: $(sec_principal_id)
            inputs:
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/networking'
              commandOptions: 'main.tfplan'
              environmentServiceName: 'Networking_Sub'