# Azure DevOps pipeline for Azure deployment

variables:
- group: globomantics

trigger:
  branches:
    include:
    - main

stages:
- stage: development
  displayName: development
  jobs:
  - deployment: deploy
    environment: development
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: '1.0.3'
      
          # Login
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'conyaem-nprd(172f7750-929c-4214-99fb-e1e8d9e582f2)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az --version
                az account list -o table
                az account show
              useGlobalConfig: true

          # Init
          - task: Bash@3
            displayName: Initialize Terraform
            env:
              ARM_SAS_TOKEN: $(sas_token)
            inputs:
              targetType: 'inline'
              workingDirectory: '$(System.DefaultWorkingDirectory)/networking'
              script: |
                terraform init -backend-config=storage_account_name=$(storage_account_name) -backend-config=container_name="terraform-state" -backend-config=key="terraform.tfstate"
      
          # Check for workspace
          - task: Bash@3
            displayName: Check for Workspace
            inputs:
              targetType: 'filePath'
              filePath: '$(System.DefaultWorkingDirectory)/networking/workspacetest.sh'
              arguments: '$(Environment.Name)'
      
          - task: Bash@3
            displayName: Plan Terraform Deployment
            env:
              TF_WORKSPACE: '$(Environment.Name)'
              TF_VAR_sec_client_secret: $(sec_client_secret)
              ARM_SAS_TOKEN: $(sas_token)
              TF_VAR_sec_sub_id: $(sec_sub_id)
              TF_VAR_sec_client_id: $(sec_client_id)
              TF_VAR_sec_tenant_id: $(sec_tenant_id)
              TF_VAR_sec_vnet_name: $(sec_vnet_name)
              TF_VAR_sec_vnet_id: $(sec_vnet_id)
              TF_VAR_sec_resource_group: $(sec_resource_group)
              TF_VAR_sec_principal_id: $(sec_principal_id)
              TF_VAR_resource_group_name: $(resource_group_name)
            inputs:
              targetType: 'inline'
              workingDirectory: '$(System.DefaultWorkingDirectory)/networking'
              script: |
                terraform plan -out main.tfplan
      
          - task: Bash@3
            displayName: Apply Terraform Deployment
            inputs:
              targetType: 'inline'
              workingDirectory: '$(System.DefaultWorkingDirectory)/networking'
              script: |
                terraform apply main.tfplan
